language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - TESTER_PHP_BIN="php-cgi"
  - TESTER_PHP_BIN="hhvm"

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -c ./tests/php.ini -s ./tests/

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done